name : "saas project deployment"

on:
  push :
    branches :
    - dev-branch


jobs:
  code-check:
    runs-on : ubuntu-latest
 
    steps:
      - name : checkout code 
        uses : actions/checkout@v3
      
      - name: uv install
        uses: astral-sh/setup-uv@v4
        with:
          version : latest
      
      - name : install dependency
        run : uv sync
      - name: Env file banao
        run: echo "${{ secrets.ENV_FILE }}" > .env
        
      - name: Server start karo
        run: |
            uv run celery -A src.celery.celery_app worker & 
            sleep 3                                           
            uv run uvicorn main:app --host 0.0.0.0 --port 8000 &  
            sleep 5                 

      - name: Debug - process check karo
        run: |
         ps aux | grep uvicorn
         ps aux | grep celery

      - name: Server health check
        run: |
         curl http://localhost:8000/health
  
  deployment :
    needs : code-check
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3   # ← YE ADD KARO SABSE PEHLE
     
      - name : docker login
        uses : docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PASS }}
      
      - name : build docker image
        uses : docker/build-push-action@v4
        with:
          context: .                              
          push: true
          tags: ${{ secrets.DOCKER_NAME }}/supportai:latest

      - name: Render pe deploy karo
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}



    